const COLOS = {
  AKL: "auckland",
  AMS: "amsterdam",
  ARN: "stockholm",
  ATH: "athens",
  ATL: "atlanta",
  AUS: "austin",
  BAH: "manama",
  BCN: "barcelona",
  BEG: "belgrade",
  BER: "berlin",
  BEY: "beirut",
  BGW: "baghdad",
  BKK: "bangkok",
  BLR: "bengaluru",
  BNA: "nashville",
  BNE: "brisbane",
  BOG: "bogotá",
  BOM: "mumbai",
  BOS: "boston",
  BRU: "brussels",
  BSB: "brasília",
  BTS: "bratislava",
  BUD: "budapest",
  BUE: "buenos aires",
  BUF: "buffalo",
  CAI: "cairo",
  CCS: "caracas",
  CCU: "kolkata",
  CDG: "paris",
  CGB: "cuiabá",
  CGK: "jakarta",
  CGO: "zhengzhou",
  CHC: "christchurch",
  CKG: "chongqing",
  CLE: "cleveland",
  CLT: "charlotte",
  CMB: "colombo",
  CMH: "columbus",
  CNF: "belo horizonte",
  CNX: "chiang mai",
  COR: "córdoba",
  CPH: "copenhagen",
  CPT: "cape town",
  CRK: "angeles city",
  CTU: "chengdu",
  CUR: "willemstad",
  CWB: "curitiba",
  DAC: "dhaka",
  DAR: "dar es salaam",
  DEL: "new delhi",
  DEN: "denver",
  DFW: "dallas",
  DKR: "dakar",
  DLA: "douala",
  DME: "moscow",
  DOH: "doha",
  DTW: "detroit",
  DUB: "dublin",
  DUR: "durban",
  DUS: "düsseldorf",
  DXB: "dubai",
  EBB: "kampala",
  EDI: "edinburgh",
  EVN: "yerevan",
  EWR: "newark",
  EZE: "buenos aires",
  FCO: "rome",
  FIH: "kinshasa",
  FJR: "fujairah",
  FLN: "florianópolis",
  FOC: "fuzhou",
  FOR: "fortaleza",
  FRA: "frankfurt",
  FUK: "fukuoka",
  GDL: "guadalajara",
  GIG: "rio de janeiro",
  GND: "saint george's",
  GOT: "gothenburg",
  GRU: "são paulo",
  GUA: "guatemala city",
  GUM: "hagåtña",
  GVA: "geneva",
  GYE: "guayaquil",
  HAM: "hamburg",
  HAN: "hanoi",
  HEL: "helsinki",
  HGH: "hangzhou",
  HKG: "hong kong",
  HND: "tokyo",
  HNL: "honolulu",
  HRE: "harare",
  HYD: "hyderabad",
  IAD: "ashburn",
  IAH: "houston",
  ICN: "seoul",
  IND: "indianapolis",
  ISB: "islamabad",
  ISP: "islip",
  IST: "istanbul",
  ITJ: "itajaí",
  ITM: "osaka",
  IXC: "chandigarh",
  JAX: "jacksonville",
  JDO: "juazeiro do norte",
  JED: "jeddah",
  JFK: "new york",
  JHB: "johor bahru",
  JIB: "djibouti",
  JNB: "johannesburg",
  KBP: "kyiv",
  KGL: "kigali",
  KHH: "kaohsiung",
  KHI: "karachi",
  KIV: "chișinău",
  KIX: "osaka",
  KJA: "krasnoyarsk",
  KTM: "kathmandu",
  KUL: "kuala lumpur",
  KWI: "kuwait city",
  LAD: "luanda",
  LAS: "las vegas",
  LAX: "los angeles",
  LCA: "nicosia",
  LED: "saint petersburg",
  LHE: "lahore",
  LHR: "london",
  LIM: "lima",
  LIS: "lisbon",
  LJU: "ljubljana",
  LOS: "lagos",
  LUX: "luxembourg city",
  LYS: "lyon",
  MAA: "chennai",
  MAD: "madrid",
  MAN: "manchester",
  MBA: "mombasa",
  MCI: "kansas city",
  MCT: "muscat",
  MDE: "medellín",
  MDW: "chicago",
  MEM: "memphis",
  MEX: "mexico city",
  MFE: "mcallen",
  MFM: "macau",
  MGM: "montgomery",
  MIA: "miami",
  MKC: "kansas city",
  MLE: "malé",
  MNL: "manila",
  MPM: "maputo",
  MRS: "marseille",
  MRU: "port louis",
  MSP: "minneapolis",
  MSQ: "minsk",
  MUC: "munich",
  MXP: "milan",
  NBO: "nairobi",
  NDJ: "n'djamena",
  NJF: "najaf",
  NNG: "nanning",
  NOU: "nouméa",
  NQN: "neuquén",
  NRT: "tokyo",
  OKA: "naha",
  OMA: "omaha",
  ORD: "chicago",
  ORF: "norfolk",
  ORK: "cork",
  OSL: "oslo",
  OTP: "bucharest",
  OUA: "ouagadougou",
  PA0: "palo alto",
  PAP: "port-au-prince",
  PBM: "paramaribo",
  PBX: "porto velho",
  PDX: "portland",
  PER: "perth",
  PHL: "philadelphia",
  PHX: "phoenix",
  PIT: "pittsburgh",
  PMO: "palermo",
  PMW: "palmas",
  PNH: "phnom penh",
  POA: "porto alegre",
  POS: "port of spain",
  PPT: "papeete",
  PRG: "prague",
  PTY: "panama city",
  QRO: "querétaro",
  QWJ: "incheon",
  RDU: "raleigh",
  REC: "recife",
  REK: "reykjavík",
  RIC: "richmond",
  RIX: "riga",
  RNO: "reno",
  ROB: "monrovia",
  RUH: "riyadh",
  SAN: "san diego",
  SAT: "san antonio",
  SCL: "santiago",
  SDQ: "santo domingo",
  SEA: "seattle",
  SFO: "san francisco",
  SGN: "ho chi minh city",
  SIN: "singapore",
  SJC: "san jose",
  SJO: "san josé",
  SJP: "são josé do rio preto",
  SJU: "san juan",
  SKG: "thessaloniki",
  SKP: "skopje",
  SLC: "salt lake city",
  SMF: "sacramento",
  SOF: "sofia",
  SSA: "salvador",
  STI: "santiago",
  STL: "saint louis",
  STR: "stuttgart",
  SVX: "yekaterinburg",
  SYD: "sydney",
  SZX: "shenzhen",
  TAS: "tashkent",
  TBS: "tbilisi",
  TGU: "tegucigalpa",
  THR: "tehran",
  TIA: "tirana",
  TLH: "tallahassee",
  TLL: "tallinn",
  TLV: "tel aviv",
  TNR: "antananarivo",
  TPA: "tampa",
  TPE: "taipei",
  TRN: "turin",
  TUN: "tunis",
  UIO: "quito",
  ULN: "ulaanbaatar",
  VCP: "campinas",
  VIE: "vienna",
  VIX: "vitória",
  VNO: "vilnius",
  WAW: "warsaw",
  WLG: "wellington",
  XAP: "chapecó",
  YHZ: "halifax",
  YOW: "ottawa",
  YQM: "moncton",
  YUL: "montreal",
  YVR: "vancouver",
  YWG: "winnipeg",
  YXE: "saskatoon",
  YYC: "calgary",
  YYZ: "toronto",
  ZAG: "zagreb",
  ZRH: "zurich",
};

export const coloCity = (code) => {
  if (!code) return "unknown";
  return COLOS[code.toUpperCase()] || code.toLowerCase();
};
